context:
  version: "0.29.0"
  python_min: "3.9"
  build_number: 1

package:
  name: pylance
  version: ${{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e138af5a6ecb13ca8d4a717560681bc02a16e37cb06e9ce827bb60bc916f63a1

build:
  number: ${{ build_number }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.3.2,<2
  host:
    - python
    - pip
    - maturin >=1.3.2,<2
    - openssl
  run:
    - python
    - numpy >=1.22
    - pyarrow >=14

tests:
  - python:
      imports:
        - lance
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/lancedb/lance

extra:
  recipe-maintainers:
    - yhori991
